#test
name: Create S3 Bucket

on:
  push:
    branches:
      - main

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}  # Defaults to us-east-1 if not specified in GitHub Secrets

    - name: Create S3 bucket
      env:
        BUCKET_NAME: my-unique-bucket-name-${{ github.run_id }}
      run: |
        aws s3 mb s3://$BUCKET_NAME
        echo "S3 bucket '$BUCKET_NAME' created successfully."
